### ISSUE TITLE
CodeCov GHAs Master tracker

### ISSUE THREAD

**Issue by tushar5526** [Unified-Learner-Passbook/ULP-devops#3]
- [ ] [Verifier MS](https://github.com/Unified-Learner-Passbook/Verifier-MS)
- [ ] [Issuer-MS](https://github.com/Unified-Learner-Passbook/Issuer-MS)
- [ ] [Cred-Schema-MS](https://github.com/Unified-Learner-Passbook/Cred-Schema-MS)
- [ ] [Credential-MS](https://github.com/Unified-Learner-Passbook/Credential-MS)
- [ ] [DID-L3-MS](https://github.com/Unified-Learner-Passbook/DID-L3-MS)
